[package]
authors = ["Aaron Trent <novacrazy@gmail.com>"]
build = "build.rs"
name = "openalsoft-sys"
version = "0.1.0"

[build-dependencies]
cmake = "0.1.20"

[dependencies]
libc = "0.2.18"

[features]
default = ["presets", "hrtf", "static"]
hrtf = []
presets = []
static = []